// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikyqawndyowdfrttttqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlreXFhd25keW93ZGZydHR0dHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNTg4MjYsImV4cCI6MjA1MTgzNDgyNn0.t4zdGPQvpr-pc_Bm6JDe2J5dXXh_DkrDasVzH97fVwQ";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);